# UV-specific configuration for Helios MCP (September 2025)
# UV 0.8.15+ with Python 3.13

# Package management
managed = true
package = true

# Python version pinning
requires-python = ">=3.13"

# Concurrent operations for performance
concurrent-builds = 4
concurrent-downloads = 50

# Index configuration
[[index]]
url = "https://pypi.org/simple"
default = true
name = "pypi"

# Development dependencies (moved to pyproject.toml [dependency-groups])
# Using dependency-groups in pyproject.toml as recommended for UV 0.8.15+

# Source overrides for specific packages
[sources]
# Example: Use latest FastMCP from GitHub if needed
# fastmcp = { git = "https://github.com/jlowin/fastmcp.git", branch = "main" }

# Build configuration
[build]
# Use uv_build backend (configured in pyproject.toml)

# Tool-specific settings
[tool.ruff]
line-length = 88
target-version = "py313"

[tool.mypy]
python_version = "3.13"
strict = true

[tool.pytest]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
